In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

# Projeto 1:

definindo a função para o metodo Analitico:

In [5]:
def matriz_defeituosa(A):
    linhas, colunas = np.shape(A)
    if linhas != colunas:
        return True
    auto_valores, auto_vetores = np.linalg.eig(A)
    if not np.all(np.isreal(auto_valores)):
        return True
    autovalores_unicos = np.unique(auto_valores)
    if len(auto_valores) != len(autovalores_unicos):
        return True
    else:
        pass

def EDO_solve(A,u0,h=0.01,num_inter=100):
    linhas, colunas = np.shape(A)
    if matriz_defeituosa(A):
        u_n = []
        epsilon=1e-10
        resultado = np.identity(colunas)
        termo = np.identity(colunas)
        i = 1
        for j in range(num_inter):
            t = h*j
            while np.max(np.abs(termo)) > epsilon:
                termo = np.dot(termo, A) * (t**i / np.math.factorial(i))
                resultado += termo
                i+=1
            print(resultado)
            u_n.append(resultado @ u0)
        return u_n
    else:
        alpha, S = np.linalg.eig(A)
        S_1 = np.linalg.inv(S)
        matriz_alpha = np.diag(alpha)
        u_n = []
        for j in range(num_inter):
            t = j * h
            for i in range(colunas):
                matriz_alpha[i, i] = np.exp(matriz_alpha[i, i] * t)
            u_t = S @ matriz_alpha @ S_1
            u_n.append(np.dot(u_t,u0))
            matriz_alpha = np.diag(alpha)
        return u_n

Definindo a função para o metodo numérico:

In [6]:
def FE(A, u0, h=0.01, num_inter=100):
    resultados = []
    u = u0
    for _ in range(num_inter):
        u_1 = u + h * np.dot(A, u)
        resultados.append(u_1)
        u = u_1
    return resultados

# Testando para matriz defeituosa:

In [7]:
A_defeituosa = np.array([[-4, -4, 1, 0, 0, 0],
                     [-4, -4, 1, 0, 0, 0],
                     [0, 0, -19, 1, 1, 0],
                     [ 0, 0, 0, -4, -4, 1],
                     [ 0, 0, 0, -4, -4, 1],
                     [ 0, 0, 0, 0, 0, -19]],)
u0 = np.array([1,1,1,1])
resultado_EDO = EDO_solve(A_defeituosa, u0)
resultado_FE = FE(A_defeituosa, u0)
pontos = np.linspace(0,1,100)
fig,(x1,x2,x3)=plt.subplots(1,3)
for i in range(A_defeituosa.shape[0]):
    u_EDO = [x[i] for x in resultado_EDO]
    u_FE = [x[i] for x in resultado_FE]
    error = [abs(abs(u_EDO[i])-abs(u_FE[i])) for i in range(0,len(u_EDO))]
    x1.plot(pontos, u_EDO, label=f'u{i}')
    x2.plot(pontos, u_FE, label=f'u{i}')
    x3.plot(pontos, error)
x1.set_title("analítica:")
x2.set_title("numérica:")
x3.set_title("Erro:")
x1.legend()
x2.legend()
plt.show()

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 6)

# Testando para matriz não defeituosa:

In [ ]:
A_nao_defeituosa = np.array([[0.6, 0.2, 0.3, 0.1],
              [0.2, 0.9, 0.1, 0.3],
              [0.3, 0.1, 0.8, 0.2],
              [0.1, 0.3, 0.2, 0.7]])
u0 = np.array([1,1,1,1])
resultado_EDO = EDO_solve(A_nao_defeituosa, u0)
resultado_FE = FE(A_nao_defeituosa, u0)
pontos = np.linspace(0,1,100)
fig,(x1,x2,x3)=plt.subplots(1,3)
for i in range(A_nao_defeituosa.shape[0]):
    u_EDO = [x[i] for x in resultado_EDO]
    u_FE = [x[i] for x in resultado_FE]
    error = [abs(abs(u_EDO[i])-abs(u_FE[i])) for i in range(0,len(u_EDO))]
    x1.plot(pontos, u_EDO, label=f'u{i}')
    x2.plot(pontos, u_FE, label=f'u{i}')
    x3.plot(pontos, error)
x1.set_title("analítica:")
x2.set_title("numérica:")
x3.set_title("Erro:")
x1.legend()
x2.legend()
plt.show()

In [ ]:
print(matriz_defeituosa(A_defeituosa))